comment:
  image:
    repository: greenlama/comment:logging
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: greenlama/post:logging
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: greenlama/ui:logging
    tag: latest
  service:
    externalPort: 9292
